import Head from "next/head";
import Image from "next/image";
import Layout from "../components/Layout";
import profilePic from "../../public/images/profile/developer-pic-1.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout>
          <div className="flex items-center justify-between w-full">
            <div>
              <Image src={profilePic} alt="TJ" className="w-full h-auto" />
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
